### ISSUE TITLE
Add Examples in C++

### ISSUE THREAD

**Issue by dataPulverizer** [cloudera/kudu-examples#17]
This library looks great. It would be good to have C++ examples. Is C++ API designed to allow the user read and write data as well as execute queries? For example construct rows in the C++ API and append them to tables and then read back query outputs?

**Comment by toddlipcon** [comment]
Hi

Please check out the sample in the main kudu repo: https://github.com/apache/incubator-kudu/blob/master/src/kudu/client/samples/sample.cc

Hopefully that one is useful for you.

-Todd

**Comment by dataPulverizer** [comment]
Thanks a lot, the code looks very informative. I have installed Kudu on an Ubuntu 14.04 system using the instructions (http://getkudu.io/docs/installation.html). I confirmed that it is running on http://localhost:8051/

I tried to compile the "sample.cc" and got an error, am I missing some compilation flags? (g++ v4.8.4)

$ g++ sample.cc -std=c++11

and got the error:
sample.cc:45:21: error: ‘kudu::client::sp’ has not been declared
 using kudu::client::sp::shared_ptr;
                     ^
sample.cc:55:28: error: ‘shared_ptr’ has not been declared
                            shared_ptr<KuduClient>* client) {
                            ^
sample.cc:55:38: error: expected ‘,’ or ‘...’ before ‘<’ token
                            shared_ptr<KuduClient>* client) {
                                      ^
sample.cc: In function ‘kudu::Status CreateClient(const string&, int)’:
sample.cc:59:14: error: ‘client’ was not declared in this scope
       .Build(client);
              ^
sample.cc:59:14: note: suggested alternative:
In file included from sample.cc:22:0:
/usr/include/kudu/client/callbacks.h:29:18: note:   ‘kudu::client’
 namespace client {
                  ^
sample.cc: At global scope:
sample.cc:74:36: error: ‘shared_ptr’ does not name a type
 static Status DoesTableExist(const shared_ptr<KuduClient>& client,
                                    ^
sample.cc:74:36: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
sample.cc:74:46: error: expected ‘,’ or ‘...’ before ‘<’ token
 static Status DoesTableExist(const shared_ptr<KuduClient>& client,
                                              ^
sample.cc: In function ‘kudu::Status DoesTableExist(int)’:
sample.cc:77:3: error: ‘shared_ptr’ was not declared in this scope
   shared_ptr<KuduTable> table;
   ^
sample.cc:77:3: note: suggested alternatives:
In file included from /usr/include/c++/4.8/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/4.8/memory:82,
                 from /usr/include/c++/4.8/tr1/memory:39,
                 from /usr/include/kudu/client/client.h:19,
                 from sample.cc:23:
/usr/include/c++/4.8/bits/shared_ptr_base.h:261:11: note:   ‘std::shared_ptr’
     class shared_ptr;
           ^
In file included from /usr/include/c++/4.8/tr1/memory:50:0,
                 from /usr/include/kudu/client/client.h:19,
                 from sample.cc:23:
/usr/include/c++/4.8/tr1/shared_ptr.h:503:11: note:   ‘std::tr1::shared_ptr’
     class shared_ptr;
           ^
sample.cc:77:23: error: expected primary-expression before ‘>’ token
   shared_ptr<KuduTable> table;
                       ^
sample.cc:77:25: error: ‘table’ was not declared in this scope
   shared_ptr<KuduTable> table;
                         ^
sample.cc:78:14: error: ‘client’ was not declared in this scope
   Status s = client->OpenTable(table_name, &table);
              ^
sample.cc:78:14: note: suggested alternative:
In file included from sample.cc:22:0:
/usr/include/kudu/client/callbacks.h:29:18: note:   ‘kudu::client’
 namespace client {
                  ^
sample.cc:78:32: error: ‘table_name’ was not declared in this scope
   Status s = client->OpenTable(table_name, &table);
                                ^
sample.cc:80:6: error: ‘exists’ was not declared in this scope
     *exists = true;
      ^
sample.cc:82:6: error: ‘exists’ was not declared in this scope
     *exists = false;
      ^
sample.cc: At global scope:
sample.cc:88:33: error: ‘shared_ptr’ does not name a type
 static Status CreateTable(const shared_ptr<KuduClient>& client,
                                 ^
sample.cc:88:33: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
sample.cc:88:43: error: expected ‘,’ or ‘...’ before ‘<’ token
 static Status CreateTable(const shared_ptr<KuduClient>& client,
                                           ^
sample.cc: In function ‘kudu::Status CreateTable(int)’:
sample.cc:94:30: error: ‘num_tablets’ was not declared in this scope
   int32_t increment = 1000 / num_tablets;
                              ^
sample.cc:96:27: error: ‘schema’ was not declared in this scope
     KuduPartialRow* row = schema.NewRow();
                           ^
sample.cc:102:37: error: ‘client’ was not declared in this scope
   KuduTableCreator* table_creator = client->NewTableCreator();
                                     ^
sample.cc:102:37: note: suggested alternative:
In file included from sample.cc:22:0:
/usr/include/kudu/client/callbacks.h:29:18: note:   ‘kudu::client’
 namespace client {
                  ^
sample.cc:103:40: error: ‘table_name’ was not declared in this scope
   Status s = table_creator->table_name(table_name)
                                        ^
sample.cc:104:16: error: ‘schema’ was not declared in this scope
       .schema(&schema)
                ^
sample.cc: At global scope:
sample.cc:111:32: error: ‘shared_ptr’ does not name a type
 static Status AlterTable(const shared_ptr<KuduClient>& client,
                                ^
sample.cc:111:32: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
sample.cc:111:42: error: expected ‘,’ or ‘...’ before ‘<’ token
 static Status AlterTable(const shared_ptr<KuduClient>& client,
                                          ^
sample.cc: In function ‘kudu::Status AlterTable(int)’:
sample.cc:113:37: error: ‘client’ was not declared in this scope
   KuduTableAlterer* table_alterer = client->NewTableAlterer(table_name);
                                     ^
sample.cc:113:37: note: suggested alternative:
In file included from sample.cc:22:0:
/usr/include/kudu/client/callbacks.h:29:18: note:   ‘kudu::client’
 namespace client {
                  ^
sample.cc:113:61: error: ‘table_name’ was not declared in this scope
   KuduTableAlterer* table_alterer = client->NewTableAlterer(table_name);
                                                             ^
sample.cc: At global scope:
sample.cc:127:32: error: ‘shared_ptr’ does not name a type
 static Status InsertRows(const shared_ptr<KuduTable>& table, int num_rows) {
                                ^
sample.cc:127:32: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
sample.cc:127:42: error: expected ‘,’ or ‘...’ before ‘<’ token
 static Status InsertRows(const shared_ptr<KuduTable>& table, int num_rows) {
                                          ^
sample.cc: In function ‘kudu::Status InsertRows(int)’:
sample.cc:128:3: error: ‘shared_ptr’ was not declared in this scope
   shared_ptr<KuduSession> session = table->client()->NewSession();
   ^
sample.cc:128:3: note: suggested alternatives:
In file included from /usr/include/c++/4.8/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/4.8/memory:82,
                 from /usr/include/c++/4.8/tr1/memory:39,
                 from /usr/include/kudu/client/client.h:19,
                 from sample.cc:23:
/usr/include/c++/4.8/bits/shared_ptr_base.h:261:11: note:   ‘std::shared_ptr’
     class shared_ptr;
           ^
In file included from /usr/include/c++/4.8/tr1/memory:50:0,
                 from /usr/include/kudu/client/client.h:19,
                 from sample.cc:23:
/usr/include/c++/4.8/tr1/shared_ptr.h:503:11: note:   ‘std::tr1::shared_ptr’
     class shared_ptr;
           ^
sample.cc:128:25: error: expected primary-expression before ‘>’ token
   shared_ptr<KuduSession> session = table->client()->NewSession();
                         ^
sample.cc:128:27: error: ‘session’ was not declared in this scope
   shared_ptr<KuduSession> session = table->client()->NewSession();
                           ^
sample.cc:128:37: error: ‘table’ was not declared in this scope
   shared_ptr<KuduSession> session = table->client()->NewSession();
                                     ^
sample.cc:132:23: error: ‘num_rows’ was not declared in this scope
   for (int i = 0; i < num_rows; i++) {
                       ^
sample.cc: At global scope:
sample.cc:165:30: error: ‘shared_ptr’ does not name a type
 static Status ScanRows(const shared_ptr<KuduTable>& table) {
                              ^
sample.cc:165:30: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
sample.cc:165:40: error: expected ‘,’ or ‘...’ before ‘<’ token
 static Status ScanRows(const shared_ptr<KuduTable>& table) {
                                        ^
sample.cc: In function ‘kudu::Status ScanRows(int)’:
sample.cc:169:23: error: ‘table’ was not declared in this scope
   KuduScanner scanner(table.get());
                       ^
sample.cc: In function ‘int main(int, char**)’:
sample.cc:248:3: error: ‘shared_ptr’ was not declared in this scope
   shared_ptr<KuduClient> client;
   ^
sample.cc:248:3: note: suggested alternatives:
In file included from /usr/include/c++/4.8/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/4.8/memory:82,
                 from /usr/include/c++/4.8/tr1/memory:39,
                 from /usr/include/kudu/client/client.h:19,
                 from sample.cc:23:
/usr/include/c++/4.8/bits/shared_ptr_base.h:261:11: note:   ‘std::shared_ptr’
     class shared_ptr;
           ^
In file included from /usr/include/c++/4.8/tr1/memory:50:0,
                 from /usr/include/kudu/client/client.h:19,
                 from sample.cc:23:
/usr/include/c++/4.8/tr1/shared_ptr.h:503:11: note:   ‘std::tr1::shared_ptr’
     class shared_ptr;
           ^
sample.cc:248:24: error: expected primary-expression before ‘>’ token
   shared_ptr<KuduClient> client;
                        ^
sample.cc:248:26: error: ‘client’ was not declared in this scope
   shared_ptr<KuduClient> client;
                          ^
sample.cc:248:26: note: suggested alternative:
In file included from sample.cc:22:0:
/usr/include/kudu/client/callbacks.h:29:18: note:   ‘kudu::client’
 namespace client {
                  ^
sample.cc:274:23: error: expected primary-expression before ‘>’ token
   shared_ptr<KuduTable> table;
                       ^
sample.cc:274:25: error: ‘table’ was not declared in this scope
   shared_ptr<KuduTable> table;
                         ^
sample.cc: In function ‘int main()’:
sample.cc:292:10: error: declaration of C function ‘int main()’ conflicts with
 int main(){
          ^
sample.cc:233:5: error: previous declaration ‘int main(int, char**)’ here
 int main(int argc, char* argv[]) {

**Comment by toddlipcon** [comment]
Hi,

I'm guessing that you're using the sample from trunk against the 0.6.0 API. Can you try again by checking out the sample code from the kudu0.6.0-release tag? (or build and install the client from trunk, but that would be a bit more work)

-Todd

**Comment by dataPulverizer** [comment]
I have just tried to compile the sample.cc code from kudu0.6.0-release tag but I get a slightly difference set of error messages. Perhaps I 'll try compiling source trunk

```
$ g++ sample.cc -o sample -std=c++11
/tmp/ccrl3oXV.o: In function `CreateClient(std::string const&, std::tr1::shared_ptr<kudu::client::KuduClient>*)':
sample.cc:(.text+0xc4): undefined reference to `kudu::MonoDelta::FromSeconds(double)'
sample.cc:(.text+0xd4): undefined reference to `kudu::client::KuduClientBuilder::KuduClientBuilder()'
sample.cc:(.text+0xe7): undefined reference to `kudu::client::KuduClientBuilder::add_master_server_addr(std::string const&)'
sample.cc:(.text+0xf6): undefined reference to `kudu::client::KuduClientBuilder::default_admin_operation_timeout(kudu::MonoDelta const&)'
sample.cc:(.text+0x10c): undefined reference to `kudu::client::KuduClientBuilder::Build(std::tr1::shared_ptr<kudu::client::KuduClient>*)'
sample.cc:(.text+0x119): undefined reference to `kudu::client::KuduClientBuilder::~KuduClientBuilder()'
sample.cc:(.text+0x12a): undefined reference to `kudu::client::KuduClientBuilder::~KuduClientBuilder()'
/tmp/ccrl3oXV.o: In function `CreateSchema()':
sample.cc:(.text+0x166): undefined reference to `kudu::client::KuduSchema::KuduSchema()'
sample.cc:(.text+0x175): undefined reference to `kudu::client::KuduSchemaBuilder::KuduSchemaBuilder()'
sample.cc:(.text+0x1ac): undefined reference to `kudu::client::KuduSchemaBuilder::AddColumn(std::string const&)'
sample.cc:(.text+0x1b9): undefined reference to `kudu::client::KuduColumnSpec::Type(kudu::client::KuduColumnSchema::DataType)'
sample.cc:(.text+0x1c1): undefined reference to `kudu::client::KuduColumnSpec::NotNull()'
sample.cc:(.text+0x1c9): undefined reference to `kudu::client::KuduColumnSpec::PrimaryKey()'
sample.cc:(.text+0x218): undefined reference to `kudu::client::KuduSchemaBuilder::AddColumn(std::string const&)'
sample.cc:(.text+0x225): undefined reference to `kudu::client::KuduColumnSpec::Type(kudu::client::KuduColumnSchema::DataType)'
sample.cc:(.text+0x22d): undefined reference to `kudu::client::KuduColumnSpec::NotNull()'
sample.cc:(.text+0x27c): undefined reference to `kudu::client::KuduSchemaBuilder::AddColumn(std::string const&)'
sample.cc:(.text+0x289): undefined reference to `kudu::client::KuduColumnSpec::Type(kudu::client::KuduColumnSchema::DataType)'
sample.cc:(.text+0x291): undefined reference to `kudu::client::KuduColumnSpec::NotNull()'
sample.cc:(.text+0x2b3): undefined reference to `kudu::client::KuduValue::FromInt(long)'
sample.cc:(.text+0x2ed): undefined reference to `kudu::client::KuduSchemaBuilder::AddColumn(std::string const&)'
sample.cc:(.text+0x2fa): undefined reference to `kudu::client::KuduColumnSpec::Type(kudu::client::KuduColumnSchema::DataType)'
sample.cc:(.text+0x302): undefined reference to `kudu::client::KuduColumnSpec::NotNull()'
sample.cc:(.text+0x30d): undefined reference to `kudu::client::KuduColumnSpec::Default(kudu::client::KuduValue*)'
sample.cc:(.text+0x342): undefined reference to `kudu::client::KuduSchemaBuilder::Build(kudu::client::KuduSchema*)'
sample.cc:(.text+0x383): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x42a): undefined reference to `kudu::client::KuduSchemaBuilder::~KuduSchemaBuilder()'
sample.cc:(.text+0x50b): undefined reference to `kudu::client::KuduSchemaBuilder::~KuduSchemaBuilder()'
sample.cc:(.text+0x51f): undefined reference to `kudu::client::KuduSchema::~KuduSchema()'
/tmp/ccrl3oXV.o: In function `DoesTableExist(std::tr1::shared_ptr<kudu::client::KuduClient> const&, std::string const&, bool*)':
sample.cc:(.text+0x587): undefined reference to `kudu::client::KuduClient::OpenTable(std::string const&, std::tr1::shared_ptr<kudu::client::KuduTable>*)'
/tmp/ccrl3oXV.o: In function `CreateTable(std::tr1::shared_ptr<kudu::client::KuduClient> const&, std::string const&, kudu::client::KuduSchema const&, int)':
sample.cc:(.text+0x6a2): undefined reference to `kudu::client::KuduSchema::NewRow() const'
sample.cc:(.text+0x6cf): undefined reference to `kudu::KuduPartialRow::SetInt32(int, int)'
sample.cc:(.text+0x716): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x7fb): undefined reference to `kudu::client::KuduClient::NewTableCreator()'
sample.cc:(.text+0x815): undefined reference to `kudu::client::KuduTableCreator::table_name(std::string const&)'
sample.cc:(.text+0x827): undefined reference to `kudu::client::KuduTableCreator::schema(kudu::client::KuduSchema const*)'
sample.cc:(.text+0x836): undefined reference to `kudu::client::KuduTableCreator::split_rows(std::vector<kudu::KuduPartialRow const*, std::allocator<kudu::KuduPartialRow const*> > const&)'
sample.cc:(.text+0x84b): undefined reference to `kudu::client::KuduTableCreator::Create()'
sample.cc:(.text+0x85c): undefined reference to `kudu::client::KuduTableCreator::~KuduTableCreator()'
/tmp/ccrl3oXV.o: In function `AlterTable(std::tr1::shared_ptr<kudu::client::KuduClient> const&, std::string const&)':
sample.cc:(.text+0x911): undefined reference to `kudu::client::KuduClient::NewTableAlterer(std::string const&)'
sample.cc:(.text+0x96a): undefined reference to `kudu::client::KuduTableAlterer::AlterColumn(std::string const&)'
sample.cc:(.text+0x979): undefined reference to `kudu::client::KuduColumnSpec::RenameTo(std::string const&)'
sample.cc:(.text+0x9dd): undefined reference to `kudu::client::KuduTableAlterer::AddColumn(std::string const&)'
sample.cc:(.text+0x9ea): undefined reference to `kudu::client::KuduColumnSpec::Type(kudu::client::KuduColumnSchema::DataType)'
sample.cc:(.text+0xa36): undefined reference to `kudu::client::KuduTableAlterer::DropColumn(std::string const&)'
sample.cc:(.text+0xa61): undefined reference to `kudu::client::KuduTableAlterer::Alter()'
sample.cc:(.text+0xa72): undefined reference to `kudu::client::KuduTableAlterer::~KuduTableAlterer()'
/tmp/ccrl3oXV.o: In function `StatusCB(void*, kudu::Status const&)':
sample.cc:(.text+0xb4c): undefined reference to `kudu::Status::ToString() const'
/tmp/ccrl3oXV.o: In function `InsertRows(std::tr1::shared_ptr<kudu::client::KuduTable> const&, int)':
sample.cc:(.text+0xbff): undefined reference to `kudu::client::KuduTable::client() const'
sample.cc:(.text+0xc14): undefined reference to `kudu::client::KuduClient::NewSession()'
sample.cc:(.text+0xc3a): undefined reference to `kudu::client::KuduSession::SetFlushMode(kudu::client::KuduSession::FlushMode)'
sample.cc:(.text+0xcaa): undefined reference to `kudu::client::KuduSession::SetTimeoutMillis(int)'
sample.cc:(.text+0xcd0): undefined reference to `kudu::client::KuduTable::NewInsert()'
sample.cc:(.text+0xd1b): undefined reference to `kudu::KuduPartialRow::SetInt32(kudu::Slice const&, int)'
sample.cc:(.text+0xd5f): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0xe38): undefined reference to `kudu::KuduPartialRow::SetInt32(kudu::Slice const&, int)'
sample.cc:(.text+0xe7c): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0xf5a): undefined reference to `kudu::KuduPartialRow::SetInt32(kudu::Slice const&, int)'
sample.cc:(.text+0xf9e): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x106c): undefined reference to `kudu::client::KuduSession::Apply(kudu::client::KuduWriteOperation*)'
sample.cc:(.text+0x10b0): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x1193): undefined reference to `kudu::client::KuduSession::Flush()'
sample.cc:(.text+0x11f8): undefined reference to `kudu::client::KuduSession::FlushAsync(kudu::client::KuduStatusCallback*)'
sample.cc:(.text+0x1229): undefined reference to `kudu::client::KuduSession::GetPendingErrors(std::vector<kudu::client::KuduError*, std::allocator<kudu::client::KuduError*> >*, bool*)'
sample.cc:(.text+0x129c): undefined reference to `kudu::client::KuduError::status() const'
sample.cc:(.text+0x12fd): undefined reference to `kudu::client::KuduError::~KuduError()'
sample.cc:(.text+0x13ba): undefined reference to `kudu::client::KuduSession::Close()'
/tmp/ccrl3oXV.o: In function `ScanRows(std::tr1::shared_ptr<kudu::client::KuduTable> const&)':
sample.cc:(.text+0x160a): undefined reference to `kudu::client::KuduScanner::KuduScanner(kudu::client::KuduTable*)'
sample.cc:(.text+0x1614): undefined reference to `kudu::client::KuduValue::FromInt(long)'
sample.cc:(.text+0x1651): undefined reference to `kudu::client::KuduTable::NewComparisonPredicate(kudu::Slice const&, kudu::client::KuduPredicate::ComparisonOp, kudu::client::KuduValue*)'
sample.cc:(.text+0x1678): undefined reference to `kudu::client::KuduScanner::AddConjunctPredicate(kudu::client::KuduPredicate*)'
sample.cc:(.text+0x16df): undefined reference to `kudu::client::KuduValue::FromInt(long)'
sample.cc:(.text+0x171c): undefined reference to `kudu::client::KuduTable::NewComparisonPredicate(kudu::Slice const&, kudu::client::KuduPredicate::ComparisonOp, kudu::client::KuduValue*)'
sample.cc:(.text+0x1743): undefined reference to `kudu::client::KuduScanner::AddConjunctPredicate(kudu::client::KuduPredicate*)'
sample.cc:(.text+0x17b9): undefined reference to `kudu::client::KuduScanner::Open()'
sample.cc:(.text+0x1854): undefined reference to `kudu::client::KuduScanner::NextBatch(std::vector<kudu::client::KuduRowResult, std::allocator<kudu::client::KuduRowResult> >*)'
sample.cc:(.text+0x191a): undefined reference to `kudu::client::KuduRowResult::GetInt32(kudu::Slice const&, int*) const'
sample.cc:(.text+0x1ae6): undefined reference to `kudu::client::KuduScanner::HasMoreRows() const'
sample.cc:(.text+0x1c21): undefined reference to `kudu::client::KuduScanner::~KuduScanner()'
sample.cc:(.text+0x1d09): undefined reference to `kudu::client::KuduScanner::~KuduScanner()'
/tmp/ccrl3oXV.o: In function `main':
sample.cc:(.text+0x20e2): undefined reference to `kudu::client::InstallLoggingCallback(kudu::client::KuduLoggingCallback*)'
sample.cc:(.text+0x211c): undefined reference to `kudu::client::SetVerboseLogLevel(int)'
sample.cc:(.text+0x21c5): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x22a3): undefined reference to `kudu::client::SetVerboseLogLevel(int)'
sample.cc:(.text+0x2342): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x2418): undefined reference to `kudu::client::KuduClient::DeleteTable(std::string const&)'
sample.cc:(.text+0x24ba): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x25ec): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x26f2): undefined reference to `kudu::client::KuduClient::OpenTable(std::string const&, std::tr1::shared_ptr<kudu::client::KuduTable>*)'
sample.cc:(.text+0x2736): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x2838): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x2963): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x2a5f): undefined reference to `kudu::client::KuduClient::DeleteTable(std::string const&)'
sample.cc:(.text+0x2aa6): undefined reference to `kudu::Status::ToString() const'
sample.cc:(.text+0x2bc5): undefined reference to `kudu::client::KuduSchema::~KuduSchema()'
sample.cc:(.text+0x2f1f): undefined reference to `kudu::client::KuduSchema::~KuduSchema()'
/tmp/ccrl3oXV.o: In function `kudu::Status::IOError(kudu::Slice const&, kudu::Slice const&, short)':
sample.cc:(.text._ZN4kudu6Status7IOErrorERKNS_5SliceES3_s[_ZN4kudu6Status7IOErrorERKNS_5SliceES3_s]+0x36): undefined reference to `kudu::Status::Status(kudu::Status::Code, kudu::Slice const&, kudu::Slice const&, short)'
/tmp/ccrl3oXV.o: In function `kudu::Status::Status(kudu::Status const&)':
sample.cc:(.text._ZN4kudu6StatusC2ERKS0_[_ZN4kudu6StatusC5ERKS0_]+0x27): undefined reference to `kudu::Status::CopyState(char const*)'
/tmp/ccrl3oXV.o: In function `kudu::Status::operator=(kudu::Status const&)':
sample.cc:(.text._ZN4kudu6StatusaSERKS0_[_ZN4kudu6StatusaSERKS0_]+0x55): undefined reference to `kudu::Status::CopyState(char const*)'
collect2: error: ld returned 1 exit status
```

**Comment by toddlipcon** [comment]
Looks like you're missing -lkudu_client in your invocation? You may also need to pass -L</path/to/where/kudu-client/is/installed>

**Comment by dataPulverizer** [comment]
Hi Todd,

I added the -lkudu_client flag and it worked. Thanks

**Comment by toddlipcon** [comment]
Great! BTW feel free to drop by our Slack (http://getkudu-slack.herokuapp.com) if more real-time conversation would be helpful.
