### ISSUE TITLE
Support docker cloudera/quickstart

### ISSUE THREAD

**Issue by syepes** [cloudera/kudu-examples#20]
Now that we have a simple way of testing Impala with Docker, It would be great to also have an image that includes the Kudu integration.

**Comment by adembo** [comment]
Could you provide a little more context? What's the "simple way of testing Impala with Docker" that you're alluding to?

**Comment by adembo** [comment]
Docker scripts have been merged into the [main Apache Kudu repository](https://github.com/apache/kudu/tree/master/docker).
