### ISSUE TITLE
Error while try to clone the repsoitory

### ISSUE THREAD

**Issue by jimcloud** [cloudera/kudu-examples#21]
git clone https://github.com/cloudera/kudu-examples.git

Initialized empty Git repository in /root/kudu_vm/kudu-examples/.git/
error: SSL: certificate subject name '*.com.com' does not match target host name 'github.com' while accessing https://github.com/cloudera/kudu-examples.git/info/refs

fatal: HTTP request failed

**Comment by adembo** [comment]
Hi Jim, this looks like it might have been a transient issue, is it still a problem for you?

**Comment by adembo** [comment]
I'm going to proactively close this since I'm confident it was a transient issue. Please reopen if it's still going on.
