### ISSUE TITLE
How to download Kudu VM for 1.2.0 version?

### ISSUE THREAD

**Issue by devender-yadav** [cloudera/kudu-examples#30]
I tried to download kudu VM using script:

```
curl -s https://raw.githubusercontent.com/cloudera/kudu-examples/master/demo-vm-setup/bootstrap.sh | bash
```

VM set up is done successfully. But kudu -version is 1.0.0

We are not able to use IN_LIST predicate with this version.

Is there any other location to download VM with latest Kudu version?

**Comment by adembo** [comment]
The VM has since been updated to use CDH 5.11 (i.e. Kudu 1.3.0).
