### ISSUE TITLE
update kudu-client

### ISSUE THREAD

**Issue by Nicholaev** [cloudera/kudu-examples#35]
Hello. The java-sample code gave me the same error as https://issues.apache.org/jira/browse/KUDU-1947. 
The kudu-client needs updating. Would you update it?
I updated it and tried to push but sounded like I need some kind of authorization.

**Comment by adembo** [comment]
Thanks for filing this issue. Sorry it took so long to get back to you; many Kudu developers were away on vacation in December.

Since you were able to make the pom.xml changes locally could you create a pull request on GitHub? I don't think you need any special authorization to do that.

**Comment by adembo** [comment]
The sample code has been migrated to the [main Apache Kudu repository](https://github.com/apache/kudu/tree/master/examples), so this issue is no longer relevant to this repo.
