### ISSUE TITLE
Java api client get data

### ISSUE THREAD

**Issue by ducquangkstn** [cloudera/kudu-examples#37]
Hi,
i'm looking at kudu java API and example but don't see any kind of get data or scan with a condition.
Is kuku 1.7 support this?

**Comment by danburkert** [comment]
Like a predicate or filter?  You can specify that using the [`KuduScannerBuilder::addPredicate`](http://kudu.apache.org/apidocs/org/apache/kudu/client/AbstractKuduScannerBuilder.html#addPredicate-org.apache.kudu.client.KuduPredicate-) method.

**Comment by ducquangkstn** [comment]
yeah, i can get the row from scanner. but i need some kind of get API from primary index.

**Comment by danburkert** [comment]
@ducquangkstn That's equivalent to setting equality predicates on the primary key columns.  Kudu will optimize that to a single row, complete with partition pruning and primary key predicate.
