### ISSUE TITLE
Is there a way to use Kudu/Impala HQL functions?

### ISSUE THREAD

**Issue by ricardogaspar2** [cloudera/kudu-examples#38]
It is possible to use predicates, but is it also possible to invoke a function about a column like in Impala/HQL but using the Kudu API?

e.g. 
```
SELECT max(col2) FROM mynamespace.table1;
```

**Comment by danburkert** [comment]
It's possible to use such functions when using Kudu tables through Impala, but there is no way to do it directly in the Kudu client APIs.
