### ISSUE TITLE
Unable to load 195 Million record into kudu table

### ISSUE THREAD

**Issue by sadeshjayraj** [cloudera/kudu-examples#39]
Hello,
I am trying to load 195M records into kudu table. I am working on 4 nodes cloudera server.On same cluster, I have configured Kudu  with 1 master and 3 tablet server.
All machines are of size 1.5 TB RAM and 48 cores. I have created external hive table which contains 195M records and I am just inserting all records from hive table to kudu (with 204 columns) table via impala shell.
But after inserting some millions of record into Kudu table, query goes into error due to some generic error.

Is there any special parameter tuning required in kudu to insert M of records.

Regards,

Sadesh Jayraj

**Comment by toddlipcon** [comment]
Better to ask this question on the Kudu user mailing list or the Cloudera community forum if you are using Cloudera. This github issue tracker is for reporting bugs with the example code.
