### ISSUE TITLE
Does kudu-client support LDAP authorization method?

### ISSUE THREAD

**Issue by LyZane** [cloudera/kudu-examples#40]
If support,show me how to achieve,thanks!

**Comment by adembo** [comment]
No, Kudu doesn't support LDAP authorization. We are working on authorization support via integration with Sentry, which you can track [here](https://issues.apache.org/jira/browse/KUDU-428).

I'm closing this issue; if you have other questions about Kudu supported features in the future, please use one of the Apache Kudu mailing lists available [here](https://kudu.apache.org/community.html).
