### ISSUE TITLE
what is KUDU_HOME??

### ISSUE THREAD

**Issue by celestewang1026** [cloudera/kudu-examples#42]
what is "KUDU_HOME" in 'kudu-examples/clients/python/setup.py',I had tried many address,but failed!

**Comment by adembo** [comment]
KUDU_HOME refers to the path to the Kudu source repository. You only need to provide it if you've built the Kudu Python client wrapper from source. If you're not doing that, just install the libkuduclient system package before running setup.py.

Note: these code examples were merged into [the main Kudu repository](https://github.com/apache/kudu/tree/master/examples/python); everything in this repo (except perhaps the quickstart VM setup scripts) is no longer maintained.
